### ISSUE TITLE
Element 'add', attribute 'ifconfig': The attribute 'ifconfig' is not allowed.

### ISSUE THREAD

**Issue by UrbanSurfers** [magecomp/magento2-image-clean#1]
HI,

after installing your module and when I try to access backend, I have this error message : 
`Element 'add', attribute 'ifconfig': The attribute 'ifconfig' is not allowed.`

I found this "ifconfig" in the /etc/adminhtml/menu.xlm file

I try on my actual Magento 2.1.7 and also on a fresh install to see if its comes from my version...

Thanks for your help I really need this option to save a lot of space and time (too bad they don't upgrade this feature in M2, it was already a big problem in M1 !!)

**Comment by oviliz** [comment]
It would be nice if @magecomp would care about this... Same thing on 2.2.2 (developer mode). :(

**Comment by magecomp** [comment]
The issue has been resolved.
